version: '3'
services:
  postgres-b:
    container_name: postgresql-b
    build:
      context: ./postgres
    volumes:
      - ./data/postgres-b:/var/lib/postgresql/data
      - ./init/postgres-b:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app

  postgres-b1:
    container_name: postgresql-b1
    build:
      context: ./postgres
    volumes:
      - ./data/postgres-b1:/var/lib/postgresql/data
      - ./init/postgres-b1:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app

  postgres-b2:
    container_name: postgresql-b2
    build:
      context: ./postgres
    volumes:
      - ./data/postgres-b2:/var/lib/postgresql/data
      - ./init/postgres-b2:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - app

networks:
  app:
